export const FETCH_LOGIN_BEGIN = 'FETCH_LOGIN_BEGIN';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const ADD_SIGNUP_BEGIN = 'ADD_SIGNUP_BEGIN';
export const ADD_SIGNUP_SUCCESS = 'ADD_SIGNUP_SUCCESS';
export const ADD_SIGNUP_FAILURE = 'ADD_SIGNUP_FAILURE';

export const FETCH_QUESTION_BEGIN = 'FETCH_QUESTION_BEGIN';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAILURE = 'FETCH_QUESTION_FAILURE';

export const ADD_SELECTED_OPTION_BEGIN = 'ADD_SELECTED_OPTION_BEGIN';
export const ADD_SELECTED_OPTION_SUCCESS = 'ADD_SELECTED_OPTION_SUCCESS';
export const ADD_SELECTED_OPTION_FAILURE = 'ADD_SELECTED_OPTION_FAILURE';

export const NEXT_PAGE = 'NEXT_PAGE';
export const FETCH_PAYMENTDETAILS_SUCCESS = 'FETCH_PAYMENTDETAILS_SUCCESS';

export const AGE_UP = 'AGE_UP';
export const AGE_DOWN = 'AGE_DOWN';

export const FORMREDUX_SUCCES='FORMREDUX_SUCCES';

export const FORM_SUBMIT='FORM_SUBMIT';

// location
export const FETCH_LOCATION_BEGIN='FETCH_LOCATION_BEGIN';
export const FETCH_LOCATION_SUCCESS='FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAILURE='FETCH_LOCATION_FAILURE';

// rst
export const FETCH_RST_BEGIN='FETCH_RST_BEGIN';
export const FETCH_RST_SUCCESS='FETCH_RST_SUCCESS';

// food
export const FETCH_FOOD_BEGIN='FETCH_FOOD_BEGIN';
export const FETCH_FOOD_SUCCESS='FETCH_FOOD_SUCCESS';